In [2]:
#Cauchy Schwarz inequality
# -1 <= (a.b)/(||a|| ||b||) <= 1
#how far two vectors are in geometric sense -> dot product
#/_a,b = 0, cos(0) = 90 degree
#Difference vector = a-b
#How big is that difference vector / seperation -> calc norm, L2 norm

In [3]:
import numpy as np
import pandas as pd
import sympy as sp
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

In [5]:
np.linalg.norm(a)

3.7416573867739413

In [6]:
np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))
# ||a||*||a|| = a.a

0.9746318461970762

In [7]:
mat = np.array([[1,2,-1,-1],
                [2,4,-2,3],
                [-1,1,-2,4]])
print(mat.shape)
mat

(3, 4)


array([[ 1,  2, -1, -1],
       [ 2,  4, -2,  3],
       [-1,  1, -2,  4]])

In [8]:
x = np.array([-1,1,1,0])
x

array([-1,  1,  1,  0])

In [9]:
np.dot(mat,x)

array([0, 0, 0])

In [10]:
T = np.array([
    [
        [74,128], [79,116], [71,116]
    ],
    [
        [78,118], [82,124], [72,128]
    ],
    [
        [84,138], [84,130], [74,120]
    ],
    [
        [82,126], [76,156], [82,132]
    ]
])
print(T.shape)
T

(4, 3, 2)


array([[[ 74, 128],
        [ 79, 116],
        [ 71, 116]],

       [[ 78, 118],
        [ 82, 124],
        [ 72, 128]],

       [[ 84, 138],
        [ 84, 130],
        [ 74, 120]],

       [[ 82, 126],
        [ 76, 156],
        [ 82, 132]]])

In [11]:
tmat = np.array([-1,1])
tmat

array([-1,  1])

In [12]:
np.dot(T, tmat)

array([[54, 37, 45],
       [40, 42, 56],
       [54, 46, 46],
       [44, 80, 50]])

In [13]:
np.average(T[0])

97.33333333333333

In [14]:
np.sum(T[1])/np.size(T[1])

100.33333333333333

In [15]:
avg = []
for i in range(3):
    avg.append(np.average(T[i]))
print(avg)

[97.33333333333333, 100.33333333333333, 105.0]


In [16]:
patient = T.reshape(3, 2, 4)
patient

array([[[ 74, 128,  79, 116],
        [ 71, 116,  78, 118]],

       [[ 82, 124,  72, 128],
        [ 84, 138,  84, 130]],

       [[ 74, 120,  82, 126],
        [ 76, 156,  82, 132]]])

In [17]:
np.sum((x[range(4)]*mat[:,range(4)]), axis=1)

array([0, 0, 0])

In [18]:
#Matrix vector multiplication can be viewed as sequence of dot products between rows of a matrix and vector.
#OR
#Linear combinations of columns of matrix, given values of vectors as the multipliers.

In [19]:
T = np.array([
    [
        [74,128], [79,116], [71,116]
    ],
    [
        [78,118], [82,124], [72,128]
    ],
    [
        [84,138], [84,130], [74,120]
    ],
    [
        [82,126], [76,156], [82,132]
    ]
])
print(T.shape)
T

(4, 3, 2)


array([[[ 74, 128],
        [ 79, 116],
        [ 71, 116]],

       [[ 78, 118],
        [ 82, 124],
        [ 72, 128]],

       [[ 84, 138],
        [ 84, 130],
        [ 74, 120]],

       [[ 82, 126],
        [ 76, 156],
        [ 82, 132]]])

In [20]:
T1 = T.transpose(1,2,0)
T1

array([[[ 74,  78,  84,  82],
        [128, 118, 138, 126]],

       [[ 79,  82,  84,  76],
        [116, 124, 130, 156]],

       [[ 71,  72,  74,  82],
        [116, 128, 120, 132]]])

In [21]:
T2 = T.transpose(1,0,2)
T2

array([[[ 74, 128],
        [ 78, 118],
        [ 84, 138],
        [ 82, 126]],

       [[ 79, 116],
        [ 82, 124],
        [ 84, 130],
        [ 76, 156]],

       [[ 71, 116],
        [ 72, 128],
        [ 74, 120],
        [ 82, 132]]])

In [22]:
T2[0]

array([[ 74, 128],
       [ 78, 118],
       [ 84, 138],
       [ 82, 126]])

In [24]:
T2[:,:,1]

array([[128, 118, 138, 126],
       [116, 124, 130, 156],
       [116, 128, 120, 132]])

In [28]:
A = np.array([[1,2,3],
             [4,5,6]])

B = np.array([[7,10],
             [8,11],
             [9,12]])

result = np.dot(A,B)
result

array([[ 50,  68],
       [122, 167]])

In [31]:
X = np.array([[0,1], [1,1]])
np.dot(T,X)

array([[[128, 202],
        [116, 195],
        [116, 187]],

       [[118, 196],
        [124, 206],
        [128, 200]],

       [[138, 222],
        [130, 214],
        [120, 194]],

       [[126, 208],
        [156, 232],
        [132, 214]]])

In [34]:
X1 = np.array([[[0,1,1], [1,1,0]]])
prod = np.dot(T,X1)
print(X1.shape)
print(prod)
prod.shape

(1, 2, 3)
[[[[128 202  74]]

  [[116 195  79]]

  [[116 187  71]]]


 [[[118 196  78]]

  [[124 206  82]]

  [[128 200  72]]]


 [[[138 222  84]]

  [[130 214  84]]

  [[120 194  74]]]


 [[[126 208  82]]

  [[156 232  76]]

  [[132 214  82]]]]


(4, 3, 1, 3)